spring:
  application:
    name: hopo
  profiles:
    group:
      dev: p1
      prod: p2
---
spring:
  h2:
    console:
      enabled: true
      path: /test
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 10MB
  config:
    activate:
      on-profile: profile1
    import: custom_dev.yml
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: hopo-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true
  show-login-endpoint: true
server:
  port: 8081